-- Birbal docs for the order-to-cash bridge
delete from warehouse.warehouse_meta where table_name in ('o2c_bridge', 'o2c_invoices', 'o2c_credit_memos', 'o2c_grn_lines', 'ref_customer_invoicing');
insert into warehouse.warehouse_meta (table_name, doc_md) values
('o2c_bridge', $doc$ORDER-TO-CASH BRIDGE (line grain) -- PO -> Invoice -> GRN -> Credit Memo, one row per posted sales invoice x ERP item, FY27 (invoice posting date >= 2026-04-01; earlier invoices have no lines in Supabase). Refreshed by select public.o2c_refresh(); loaded_at is not stored, check max(invoice_date). Use this for "was the invoice received in full", "what is short and not yet credited", "which invoices did PO X produce". For invoice-level answers prefer o2c_invoices (same logic rolled up).

PO -> INVOICE. po_number is the customer PO with trailing junk removed (the ERP re-invoices a cancelled invoice under the same PO plus a suffix such as . ` ' _ ; po_number_raw keeps the original, po_suffixed = true marks these). po_invoice_pattern comes from ref_customer_invoicing: ONE_PO_ONE_INVOICE for every marketplace except First Club and for most trade accounts; ONE_PO_MANY_INVOICES for Reliance / Milkbasket, Nature's Basket, Namdhari's, Metro Cash & Carry, First Club and a few small trade accounts, where one PO is served by several invoices over days or weeks -- there, count invoices per PO, never assume one. invoice_status = LIVE or CANCELLED; a cancelled invoice carries cancellation_cm_no (the corrective credit memo) and replacement_invoice_no (the later live invoice on the same PO, 191 of 198 cases); the replacement carries replaces_invoice_no. Never add a cancelled invoice to sales. po_qty is the PO quantity as entered on the invoice line, invoiced_qty is what we billed (the ERP line Quantity), invoiced_value is ex-GST line amount. erp_item_no is the CURRENT item code: the ERP still posts about 7% of invoice and credit-memo lines under the old FG code of a renamed item, so invoice lines, GRN rows and credit-memo lines are all mapped through item_rename_map before they are compared (o2c_invoice_lines keeps the posted code in erp_item_no_raw).

INVOICE -> GRN. The partner GRN feeds are matched to the invoice by grn_match_method: invoice_exact (the feed carries our invoice number), invoice_core+po (the feed mangles the number -- '27 MUM-008049', '07685' -- so the 5-digit core plus the PO number is used), invoice_core, po_unique (1 PO : 1 invoice customers whose feed has no invoice number, e.g. Blinkit BCPL hot_grn), po+item+qty / po+item+date (1 PO : many invoices customers when the feed quotes the partner's own document number, e.g. Milkbasket 'MHB/26-27/15357'), po_ambiguous (could not be decided; treat as unknown). grn_coverage says what the GRN can tell you: ITEM_QTY (grn_qty is the partner's received/accepted units for this item, one copy per GRN row -- grn_duplicate_rows counts copies the feed loaded twice), ITEM_NOT_IN_GRN (the invoice's GRN was found and every item in it is identified, but this item is not in it: the partner did not receive it, so short_qty = invoiced_qty -- the SHGRN credit memos that exist for such lines credit the full quantity), INVOICE_ONLY (a GRN exists for the invoice but this item cannot be judged: Reliance's feed has no item lines, or some feed item codes are unmapped), NOT_FOUND (the customer has a feed but nothing matched this invoice), NO_FEED (no GRN feed in Supabase: DMart, Metro Cash & Carry (received but not loaded), First Club, and trade accounts other than Nature's Basket and the Reliance stores -- the business receives no GRN from those), CANCELLED_INVOICE. Amazon (amazon_grn) and Zepto (zepto_grn) come from portal reports pasted into Google Sheets and are matched by PO + item; a Zepto PO still pending acknowledgement / ASN / GRN, or an Amazon PO still Unconfirmed, shows as INVOICE_ONLY with the pending state in grn_reject_reason rather than as short. short_qty = invoiced_qty - grn_qty when positive, short_value at the invoice unit price, excess_qty when the partner booked more than invoiced (a second GRN on the same invoice line, or a re-receipt; treat as received in full). grn_rejected_qty / grn_reject_reason come from BigBasket, Nature's Basket and Blinkit ZHPL (damaged).

GRN -> CREDIT MEMO. shgrn_cm_nos / shgrn_cm_qty / shgrn_cm_value are the SHORT-GRN credit memos (reason code SHGRN) linked to this invoice and item. credit_status: GRN_FULL (received in full), SHORT_CREDITED (short and a SHGRN credit memo covers it), SHORT_PARTIALLY_CREDITED, SHORT_CREDIT_PENDING (short units with no credit memo yet -- the list finance should chase; recent invoices may simply be waiting), NOT_IN_GRN_CREDIT_PENDING (the whole item is missing from the partner's GRN and no credit memo exists -- the same chase list, kept separate because the shortage is inferred from absence rather than measured), SHORT_CREDITED_AT_INVOICE_LEVEL (a SHGRN memo exists on the invoice but not for this item), CREDITED_WITHOUT_SHORTAGE (memo issued although the GRN shows full receipt -- review), CREDITED_NO_GRN_VISIBILITY (a SHGRN memo exists but the feed cannot show the receipt), GRN_NOT_AVAILABLE (nothing to judge from), INVOICE_CANCELLED. Expiry returns, damage, INC, capping and reconciliation credit memos are NOT in this table; see o2c_credit_memos.

Columns: po_number, po_number_raw, po_suffixed, platform, customer_no, customer_name, customer_search_name, po_invoice_pattern, ship_to_code, ship_to_name, warehouse_code, so_no, invoice_no, invoice_date, invoice_status, cancellation_cm_no, replacement_invoice_no, replaces_invoice_no, erp_item_no, item_name, item_category, po_qty, invoiced_qty, unit_price, invoiced_value, grn_feed, grn_nos, grn_date, grn_qty, grn_rejected_qty, grn_reject_reason, grn_duplicate_rows, grn_match_method, grn_coverage, short_qty, excess_qty, short_value, shgrn_cm_nos, shgrn_cm_qty, shgrn_cm_value, credit_status$doc$),
('o2c_invoices', $doc$ORDER-TO-CASH BRIDGE (invoice grain) -- one row per posted sales invoice, FY27, rolled up from o2c_bridge: PO, customer, invoice status and replacement chain, item_lines, po_qty, invoiced_qty, invoiced_value, GRN feed / numbers / date / received qty, short_qty, excess_qty, short_value, SHORT-GRN credit memos and a single credit_status (worst line wins: INVOICE_CANCELLED > SHORT_CREDIT_PENDING > NOT_IN_GRN_CREDIT_PENDING > SHORT_PARTIALLY_CREDITED > SHORT_CREDITED > CREDITED_NO_GRN_VISIBILITY > GRN_FULL; PARTLY_VISIBLE_GRN_FULL = every visible line was received in full but some lines are not visible in the feed; GRN_NOT_AVAILABLE = no receipt data at all). lines_not_in_grn counts items absent from the partner's GRN. grn_coverage here is the weakest line's coverage. Same meanings as o2c_bridge, see that doc. Count invoices with count(*), POs with count(distinct (customer_no, po_number)).

Columns: po_number, po_number_raw, po_suffixed, platform, customer_no, customer_name, customer_search_name, po_invoice_pattern, ship_to_code, ship_to_name, warehouse_code, so_no, invoice_no, invoice_date, invoice_status, cancellation_cm_no, replacement_invoice_no, replaces_invoice_no, item_lines, po_qty, invoiced_qty, invoiced_value, grn_feed, grn_nos, grn_date, grn_qty, short_qty, excess_qty, short_value, lines_not_in_grn, grn_coverage, shgrn_cm_nos, shgrn_cm_qty, shgrn_cm_value, credit_status$doc$),
('o2c_credit_memos', $doc$LIVE ERP -- every posted sales credit memo from FY27 (posting date >= 2026-04-01) categorised and linked to the invoice it credits. category: INVOICE_CANCELLATION (the corrective memo behind a cancelled invoice; the invoice is re-issued under the same PO with a suffix), SHORT_GRN (partner received less than invoiced; the memo that closes o2c_bridge short lines), EXPIRY_RETURN (stock returned at expiry -- the largest category by value, not tied to a specific invoice), DAMAGE, INC, FR, RECONCILIATION (RECO-CN), CAPPING_RETURN (Instamart return-to-vendor 'BAKERS-..RTV' documents), UNSPECIFIED. invoice_no / link_method: applies_to (the ERP Applies-to Doc No.), document_ref (External Document No. or PRN Document No. is our invoice number), po_unique (External Document No. is a PO with exactly one live invoice); null = not attributable to one invoice (normal for expiry and capping returns). po_number is the linked invoice's PO, else the memo's external document number cleaned. credit_memo_amount is the amount to customer. Never add credit memos to invoices; subtract.

Columns: credit_memo_no, customer_no, customer_name, credit_memo_date, credit_memo_amount, reason_code, is_cancellation, applies_to_doc_no, applies_to_doc_type, external_document_no, prn_document_no, prn_document_date, warehouse_code, category, invoice_no, link_method, po_number, platform$doc$),
('o2c_grn_lines', $doc$LIVE GRN, normalised -- every row of every partner GRN feed (hot_grn = Blinkit BCPL, hyperpure_grn = Blinkit ZHPL, instamart_grn, milkbasket_grn = Milkbasket, reliance_grn = Reliance Signature and Smart stores (header-level, no items), nb_grn = Nature's Basket, mraws_grn + mrgrn_grn = More Retail, bb_alert_grn + bb_net_grn = BigBasket, flipkart_cb_grn / flipkart_ppr_grn / fatema_grn / slveggies_grn = Flipkart Minutes, matched on PO number across every fulfilment-partner entity, zepto_grn and amazon_grn = portal reports pasted into Google Sheets, matched by PO + item) in one shape, with the PO number cleaned, the invoice reference the partner quoted (invoice_ref_raw), the FY27 invoice it resolved to (invoice_no, match_method; null when the partner quoted a pre-April-2026 invoice, a document number of their own, or nothing), the feed's item code and its ERP item (erp_item_no via ref_platform_item_map; null = unmapped), received_qty (accepted units), ordered_qty, rejected_qty and reject_reason where the feed has them. Use it to audit a single invoice's receipt or to see what a partner quoted. For totals use o2c_bridge, which sums these per invoice x item. No GRN exists for DMart, Metro (received, not loaded), First Club or trade accounts other than Nature's Basket and the Reliance stores.

Columns: feed, platform, po_number, invoice_ref_raw, invoice_no, match_method, grn_no, grn_date, feed_item_code, erp_item_no, received_qty, ordered_qty, rejected_qty, reject_reason, source_file$doc$),
('ref_customer_invoicing', $doc$LIVE MASTER (business config). One row per ERP customer that has invoiced since April 2026: po_invoice_pattern (ONE_PO_ONE_INVOICE or ONE_PO_MANY_INVOICES -- Reliance / Milkbasket, Nature's Basket, Namdhari's, Metro Cash & Carry, First Club and a few small trade accounts; named by the business or observed as >= 5% of POs with more than one live invoice), grn_feed (which GRN table covers the customer; null = no GRN feed in Supabase) and grn_match_rule (how o2c_bridge ties that feed to invoices), with the observed statistics behind the tag: pos_since_apr26, invoices_since_apr26, inv_per_po, max_invoices_per_po, pct_pos_multi_invoice. platform is the channel_map platform (Trade when none). reviewed = true once a person has confirmed the row; re-pushes never overwrite reviewed rows. Columns: customer_no, customer_name, search_name, platform, po_invoice_pattern, grn_feed, grn_match_rule, pos_since_apr26, invoices_since_apr26, inv_per_po, max_invoices_per_po, pct_pos_multi_invoice, note, reviewed, updated_at$doc$);
