"""
generate_config_from_excel.py

Reads the Business Central "Web Services" export (the Excel file you get from
BC's Web Services page: Tenant Admin Center > ... > Web Services > Export List)
and regenerates config/web_services.json.

Run this any time you add/remove a web service in Business Central and export
a fresh copy of the list, instead of hand-editing the JSON.

Usage:
    python scripts/generate_config_from_excel.py path/to/Web_Services.xlsx
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = ROOT / "config" / "web_services.json"

# IMPORTANT: flattened "_Excel" page web services do NOT reliably expose
# SystemId / SystemModifiedAt (BC returns 400 for fields the page doesn't
# surface). So the generator emits conservative placeholders that you MUST
# review per service:
#   - primary_key:       the business key (e.g. No / Entry_No), NOT SystemId
#   - history_field:     a populated business date for backfill chunking
#   - incremental_field: the field the incremental watermark filters on
# The startup PK guard in sync_service warns if primary_key doesn't match a
# table's actual key, so a wrong guess here surfaces loudly rather than
# silently failing inserts.
DEFAULT_PRIMARY_KEY = "No"
DEFAULT_HISTORY_FIELD = "Posting_Date"
DEFAULT_INCREMENTAL_FIELD = "Posting_Date"
DEFAULT_CHUNK = "monthly"
DEFAULT_SYNC_START = "2024-01-01"


def normalize_table_name(service_name: str) -> str:
    """Turn a BC service name into a safe, predictable Postgres table name."""
    name = service_name.strip()
    name = re.sub(r"[^0-9a-zA-Z_]+", "_", name)
    name = re.sub(r"_+", "_", name).strip("_").lower()
    # Drop a trailing "_excel" suffix that BC web service names commonly carry
    name = re.sub(r"_excel$", "", name)
    return f"bc_{name}"


def main(excel_path: str) -> None:
    df = pd.read_excel(excel_path)
    df.columns = [str(c).strip() for c in df.columns]

    required_cols = {"Object Type", "Object ID", "Object Name", "Service Name", "Published"}
    missing = required_cols - set(df.columns)
    if missing:
        raise ValueError(f"Excel file is missing expected columns: {missing}")

    services = []
    for _, row in df.iterrows():
        if str(row.get("Published")).strip().upper() not in ("TRUE", "1", "YES"):
            continue  # skip unpublished web services

        service_name = str(row["Service Name"]).strip()
        if not service_name or service_name.lower() == "nan":
            continue

        services.append(
            {
                "name": service_name,
                "display_name": str(row["Object Name"]).strip(),
                "object_type": str(row["Object Type"]).strip(),
                "object_id": int(row["Object ID"]),
                "table_name": normalize_table_name(service_name),
                "primary_key": DEFAULT_PRIMARY_KEY,
                "history_field": DEFAULT_HISTORY_FIELD,
                "incremental_field": DEFAULT_INCREMENTAL_FIELD,
                "incremental_is_datetime": False,
                "chunk": DEFAULT_CHUNK,
                "lookback_days": 7,
                "sync_start_date": DEFAULT_SYNC_START,
                "enabled": True,
            }
        )

    if not services:
        raise ValueError("No published web services found in the Excel file.")

    config = {
        "_comment": (
            "Auto-generated by scripts/generate_config_from_excel.py. "
            "BC_TENANT_ID / BC_ENVIRONMENT / BC_COMPANY_ID come from .env at "
            "runtime — no tenant or company values are hardcoded here. "
            "REVIEW per service: primary_key (business key, not SystemId), "
            "history_field (a populated date for backfill chunking), "
            "incremental_field (+ incremental_is_datetime if it is a datetime "
            "such as SystemCreatedAt), chunk, lookback_days, sync_start_date."
        ),
        "services": services,
    }

    OUTPUT_PATH.write_text(json.dumps(config, indent=2), encoding="utf-8")
    print(f"Wrote {len(services)} service(s) to {OUTPUT_PATH}")
    for svc in services:
        print(f"  - {svc['name']} -> {svc['table_name']}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python scripts/generate_config_from_excel.py <path-to-excel>")
        sys.exit(1)
    main(sys.argv[1])
